[app]
name = "uku"
title = "Uku"
id = "xyz.waozi.uku"

[paths]
flint = "vendor/flint"

[sources]
app = ["src/main.c"]

[assets]
locales = "locales/*.txt"
fonts = ["assets/fonts/ui.png", "assets/fonts/ui.dat"]

[raylib]
audio = false
models = false
graphics = "gles2"

[platform.linux]
arches = ["x86_64", "aarch64"]
