.DEFAULT_GOAL := all

APP_NAME := uku
ANDROID_APP_ID := xyz.waozi.uku
SRC := src/main.c
FLINT_DIR := vendor/flint
FLINT_MAKE_DIR := $(FLINT_DIR)/mk/
FLINT_USE_SYSTEM_CURL := 0

FLINT_RAYLIB_MODULE_AUDIO := FALSE
FLINT_NATIVE_SUPPORT_FLAGS := -DSUPPORT_MODULE_RAUDIO=0
APP_RAYLIB_CONFIG := $(RAY_RAYLIB_CONFIG) -DSUPPORT_MODULE_RAUDIO=0

include $(FLINT_MAKE_DIR)common.mk

LINUX_BIN_DIR := $(BUILD_DIR)/linux
FLINT_VENDOR_BUILD_DIR := $(BUILD_DIR)/vendor
FLINT_LIBOQS_BUILD_DIR := $(FLINT_VENDOR_BUILD_DIR)/liboqs
FLINT_CURL_BUILD_TYPE := Release
FLINT_LIBRESSL_BUILD_TYPE := Release

include $(FLINT_MAKE_DIR)vendor.mk

FLINT_NATIVE_DEPS := $(FLINT_LIBOQS_A) $(FLINT_CURL_SO)
FLINT_NATIVE_CFLAGS := $(FLINT_LIBOQS_INCLUDE) $(FLINT_CURL_CFLAGS) -DFLINT_HAS_LIBOQS=1
FLINT_NATIVE_LDLIBS := $(FLINT_LIBOQS_A) $(FLINT_CURL_LDLIBS) -lsqlite3

include $(FLINT_MAKE_DIR)raylib.mk
include $(FLINT_MAKE_DIR)native.mk
include $(FLINT_MAKE_DIR)dist.mk
include $(FLINT_MAKE_DIR)clean.mk

linux: native

dist: dist-linux

.PHONY: all native linux dist run clean
