[package]
name = "Uku"
entry = "src/app.zi"
module_roots = ["src"]
bridge_modules = ["app"]

[toolchain]
git = "https://github.com/ziranlang/ziran.git"
ref = "master"

[dependencies.Kryon]
git = "https://github.com/kryonlabs/kryon.git"
ref = "master"

[tool.Kryon]
default_profile = "desktop"

[tool.Kryon.profiles.desktop]
backend = "desktop"

[tool.Kryon.profiles.canvas]
backend = "canvas"
