#!/usr/bin/env python3
"""Write src/locale_catalogs.zi from locales/*.txt.

Every host gets the catalogs as Ziran code, so none reads files.
Run with --check to fail when the generated module is out of date.
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "locale_catalogs.zi"


def literal(text):
    escaped = (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r", "")
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return '"' + escaped + '"'


def parse(text):
    """Read a catalog: a "[key]" line, its text lines,
    and a "---" line. Trailing newlines of a value are dropped."""
    entries = []
    key = None
    value_lines = []
    for line in text.split("\n"):
        line = line.rstrip("\r")
        if line.startswith("---"):
            if key is not None:
                entries.append((key, "\n".join(value_lines).rstrip("\n")))
            key = None
            value_lines = []
        elif len(line) >= 3 and line[0] == "[" and line[-1] == "]":
            key = line[1:-1]
            value_lines = []
        elif key is not None:
            value_lines.append(line)
    if key is not None:
        entries.append((key, "\n".join(value_lines).rstrip("\n")))
    return entries


def generate():
    index = (ROOT / "locales" / "index.txt").read_text(encoding="utf-8")
    codes = [line.split("|", 1)[0] for line in index.splitlines() if "|" in line]
    lines = [
        "// Generated by scripts/generate_locales.py from locales/*.txt. Do not edit.",
        '#import "locale_entries"',
        "",
        "LocaleIndexText :: () -> string {",
        "    return " + literal(index),
        "}",
    ]
    for code in codes:
        catalog = (ROOT / "locales" / f"{code}.txt").read_text(encoding="utf-8")
        lines.append("")
        lines.append(f"LocaleFill_{code} :: () {{")
        for key, value in parse(catalog):
            lines.append(f"    LocaleAdd({literal(key)}, {literal(value)})")
        lines.append("}")
    lines.append("")
    lines.append("// Fills locale_filling for a language code; false for an unknown code.")
    lines.append("LocaleCatalogFill :: (code: string) -> bool {")
    lines.append("    locale_filling.count = 0")
    for code in codes:
        lines.append(f'    if code == "{code}" {{')
        lines.append(f"        LocaleFill_{code}()")
        lines.append("        return true")
        lines.append("    }")
    lines.append("    return false")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    text = generate()
    if "--check" in sys.argv[1:]:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != text:
            print("src/locale_catalogs.zi is out of date; run scripts/generate_locales.py")
            return 1
        return 0
    OUTPUT.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
